CREATE TABLE notebooks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL UNIQUE,
    description VARCHAR(300) NOT NULL,
    routing_summary VARCHAR(500) NULL,
    include_examples VARCHAR(2000) NULL,
    exclude_examples VARCHAR(2000) NULL,
    last_summary_refresh_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    notebook_id BIGINT NULL,
    raw_text VARCHAR(500000) NOT NULL,
    title VARCHAR(200) NOT NULL,
    summary_short VARCHAR(500) NOT NULL,
    note_type VARCHAR(64) NOT NULL,
    schema_version VARCHAR(32) NOT NULL,
    document_json VARCHAR(500000) NOT NULL,
    editor_state_json VARCHAR(500000) NOT NULL,
    current_revision_id BIGINT NULL,
    source_type VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_notes_notebook FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
);

CREATE TABLE facts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL,
    notebook_id BIGINT NOT NULL,
    key_name VARCHAR(128) NOT NULL,
    value_type VARCHAR(24) NOT NULL,
    value_number NUMERIC(14,4) NULL,
    value_text VARCHAR(4000) NULL,
    value_datetime TIMESTAMP WITH TIME ZONE NULL,
    unit VARCHAR(24) NULL,
    confidence DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_facts_note FOREIGN KEY (note_id) REFERENCES notes (id)
);

CREATE TABLE clarification_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    question VARCHAR(512) NOT NULL,
    options_json VARCHAR(2000) NOT NULL,
    status VARCHAR(16) NOT NULL,
    resolved_option VARCHAR(256) NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_clarification_note FOREIGN KEY (note_id) REFERENCES notes (id)
);

CREATE TABLE routing_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase VARCHAR(256) NOT NULL,
    notebook_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_feedback_notebook FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
);

CREATE TABLE pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notebook_id BIGINT NOT NULL,
    title VARCHAR(128) NOT NULL,
    content_current VARCHAR(20000) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_pages_notebook FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
);

CREATE TABLE page_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id BIGINT NOT NULL,
    content_snapshot VARCHAR(500000) NOT NULL,
    source_note_ids VARCHAR(1000) NOT NULL,
    model_confidence DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_revision_page FOREIGN KEY (page_id) REFERENCES pages (id)
);

CREATE TABLE attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL,
    file_name VARCHAR(300) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_attachment_note FOREIGN KEY (note_id) REFERENCES notes (id)
);

CREATE TABLE chat_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    message VARCHAR(12000) NOT NULL,
    selected_notebook_id BIGINT NULL,
    selected_note_id BIGINT NULL,
    route_plan_json VARCHAR(500000) NULL,
    patch_plan_json VARCHAR(500000) NULL,
    apply_result_json VARCHAR(500000) NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_chat_events_notebook FOREIGN KEY (selected_notebook_id) REFERENCES notebooks (id),
    CONSTRAINT fk_chat_events_note FOREIGN KEY (selected_note_id) REFERENCES notes (id)
);

CREATE TABLE note_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL,
    revision_number BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    summary_short VARCHAR(500) NOT NULL,
    document_json VARCHAR(500000) NOT NULL,
    editor_state_json VARCHAR(500000) NOT NULL,
    source_chat_event_id BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_note_revisions_note FOREIGN KEY (note_id) REFERENCES notes (id),
    CONSTRAINT fk_note_revisions_chat_event FOREIGN KEY (source_chat_event_id) REFERENCES chat_events (id)
);

CREATE TABLE document_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL,
    chat_event_id BIGINT NULL,
    operation_kind VARCHAR(64) NOT NULL,
    before_revision_id BIGINT NULL,
    after_revision_id BIGINT NOT NULL,
    provider_name VARCHAR(64) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    prompt_version VARCHAR(128) NOT NULL,
    route_confidence DOUBLE PRECISION NOT NULL,
    diff_json VARCHAR(500000) NOT NULL,
    provenance_json VARCHAR(500000) NOT NULL,
    undone_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_document_operations_note FOREIGN KEY (note_id) REFERENCES notes (id),
    CONSTRAINT fk_document_operations_chat_event FOREIGN KEY (chat_event_id) REFERENCES chat_events (id),
    CONSTRAINT fk_document_operations_before_revision FOREIGN KEY (before_revision_id) REFERENCES note_revisions (id),
    CONSTRAINT fk_document_operations_after_revision FOREIGN KEY (after_revision_id) REFERENCES note_revisions (id)
);

CREATE INDEX idx_notes_user_notebook_created ON notes (user_id, notebook_id, created_at DESC);
CREATE INDEX idx_notes_notebook_occured ON notes (notebook_id, occurred_at);
CREATE INDEX idx_facts_notebook_key_created ON facts (notebook_id, key_name, created_at);
CREATE INDEX idx_clarification_status_created ON clarification_tasks (status, created_at);
CREATE INDEX idx_chat_events_created ON chat_events (created_at DESC);
CREATE INDEX idx_note_revisions_note_created ON note_revisions (note_id, created_at DESC);
CREATE INDEX idx_document_operations_note_created ON document_operations (note_id, created_at DESC);
