CREATE TABLE notebooks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL UNIQUE,
    description VARCHAR(300) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    notebook_id BIGINT NULL,
    raw_text VARCHAR(20000) NOT NULL,
    source_type VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_notes_notebook FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
);

CREATE TABLE facts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL,
    notebook_id BIGINT NOT NULL,
    key_name VARCHAR(128) NOT NULL,
    value_type VARCHAR(24) NOT NULL,
    value_number NUMERIC(14,4) NULL,
    value_text VARCHAR(4000) NULL,
    value_datetime TIMESTAMP WITH TIME ZONE NULL,
    unit VARCHAR(24) NULL,
    confidence DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_facts_note FOREIGN KEY (note_id) REFERENCES notes (id)
);

CREATE TABLE clarification_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    question VARCHAR(512) NOT NULL,
    options_json VARCHAR(2000) NOT NULL,
    status VARCHAR(16) NOT NULL,
    resolved_option VARCHAR(256) NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fk_clarification_note FOREIGN KEY (note_id) REFERENCES notes (id)
);

CREATE TABLE routing_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase VARCHAR(256) NOT NULL,
    notebook_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_feedback_notebook FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
);

CREATE TABLE pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notebook_id BIGINT NOT NULL,
    title VARCHAR(128) NOT NULL,
    content_current VARCHAR(20000) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_pages_notebook FOREIGN KEY (notebook_id) REFERENCES notebooks (id)
);

CREATE TABLE page_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id BIGINT NOT NULL,
    content_snapshot VARCHAR(20000) NOT NULL,
    source_note_ids VARCHAR(1000) NOT NULL,
    model_confidence DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_revision_page FOREIGN KEY (page_id) REFERENCES pages (id)
);

CREATE TABLE attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL,
    file_name VARCHAR(300) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_attachment_note FOREIGN KEY (note_id) REFERENCES notes (id)
);

CREATE INDEX idx_notes_user_notebook_created ON notes (user_id, notebook_id, created_at DESC);
CREATE INDEX idx_notes_notebook_occured ON notes (notebook_id, occurred_at);
CREATE INDEX idx_facts_notebook_key_created ON facts (notebook_id, key_name, created_at);
CREATE INDEX idx_clarification_status_created ON clarification_tasks (status, created_at);
