-- Routing index tables: derived from notes/notebooks, rebuildable and disposable.
-- These power hybrid retrieval for AI routing decisions.
-- Note: pgvector extension and embedding columns are added only when running on Postgres.
-- H2 mode uses text-based lexical matching only.

CREATE TABLE note_routing_index (
    note_id BIGINT PRIMARY KEY,
    notebook_id BIGINT NULL,
    source_revision_id BIGINT NULL,
    note_family VARCHAR(64) NOT NULL,
    title VARCHAR(500) NOT NULL,
    scope_summary VARCHAR(300) NULL,
    entity_tags VARCHAR(4000) NULL,
    aliases VARCHAR(2000) NULL,
    activity_status VARCHAR(20) NOT NULL DEFAULT 'active',
    lexical_text VARCHAR(500000) NULL,
    refreshed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_nri_note FOREIGN KEY (note_id) REFERENCES notes (id) ON DELETE CASCADE,
    CONSTRAINT fk_nri_notebook FOREIGN KEY (notebook_id) REFERENCES notebooks (id) ON DELETE SET NULL
);

CREATE TABLE note_section_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL,
    section_id VARCHAR(100) NOT NULL,
    section_kind VARCHAR(50) NOT NULL,
    ordinal INT NOT NULL,
    entity_tags VARCHAR(4000) NULL,
    section_digest VARCHAR(500) NULL,
    refreshed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_nsi_note FOREIGN KEY (note_id) REFERENCES notes (id) ON DELETE CASCADE
);

CREATE INDEX idx_nsi_note ON note_section_index (note_id);

CREATE TABLE notebook_routing_index (
    notebook_id BIGINT PRIMARY KEY,
    scope_summary VARCHAR(500) NULL,
    entity_tags VARCHAR(4000) NULL,
    preferred_families VARCHAR(500) NULL,
    lexical_text VARCHAR(500000) NULL,
    refreshed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_nbri_notebook FOREIGN KEY (notebook_id) REFERENCES notebooks (id) ON DELETE CASCADE
);

CREATE INDEX idx_nri_activity ON note_routing_index (activity_status, refreshed_at DESC);
CREATE INDEX idx_nri_notebook ON note_routing_index (notebook_id);
